Repository AasmundN/mac-unit, pull requests merged in 2023-10, with the labels that each got.

#11 feat: 3AND gate
  spice/src/circuits/gates.cir
  spice/src/main.cir
Labels: enhancement

#12 feat: mux
  spice/src/circuits/gates.cir
  spice/src/circuits/mux.cir
  spice/src/inlcludes.cir.example
  spice/src/main.cir
Labels: bug, enhancement

#14 feat: d-flip-flop
  spice/src/circuits/d-flip-flop.cir
  spice/src/circuits/d-latch.cir
  spice/src/circuits/gates.cir
  spice/src/inlcludes.cir.example
  spice/src/main.cir
Labels: enhancement

#17 feat: one bit register
  .gitignore
  spice/plots/control-logic.png
  spice/plots/d-flip-flop.png
  spice/plots/main.py
  spice/plots/one-bit-register-FF.png
  spice/plots/one-bit-register-SS.png
  spice/plots/one-bit-register-TT.png
  spice/simulations/d-flip-flop.csv
  spice/simulations/one-bit-register-FF.csv
  spice/simulations/one-bit-register-SS.csv
  spice/simulations/one-bit-register-TT.csv
  spice/src/circuits/gates.cir
  spice/src/circuits/mux.cir
  spice/src/circuits/one-bit-register.cir
  spice/src/inlcludes.cir.example
  spice/src/main.cir
Labels: enhancement

#22 feat: spice simulations for all corners
  spice/plots/T0/T0_FF.png
  spice/plots/T0/T0_FS.png
  spice/plots/T0/T0_SF.png
  spice/plots/T0/T0_SS.png
  spice/plots/T0/T0_TT.png
  spice/plots/T27/T27_FF.png
  spice/plots/T27/T27_FS.png
  spice/plots/T27/T27_SF.png
  spice/plots/T27/T27_SS.png
  spice/plots/T27/T27_TT.png
  spice/plots/T70/T70_FF.png
  spice/plots/T70/T70_FS.png
  spice/plots/T70/T70_SF.png
  spice/plots/T70/T70_SS.png
  spice/plots/T70/T70_TT.png
  spice/plots/control-logic.png
  spice/plots/d-flip-flop.png
  spice/plots/main.py
  spice/plots/one-bit-register-FF.png
  spice/plots/one-bit-register-SS.png
  spice/plots/one-bit-register-TT.png
  spice/simulations/T0/T0_FF.csv
  spice/simulations/T0/T0_FS.csv
  spice/simulations/T0/T0_SF.csv
  spice/simulations/T0/T0_SS.csv
  spice/simulations/T0/T0_TT.csv
  spice/simulations/T27/T27_FF.csv
  spice/simulations/T27/T27_FS.csv
  spice/simulations/T27/T27_SF.csv
  spice/simulations/T27/T27_SS.csv
  spice/simulations/T27/T27_TT.csv
  spice/simulations/T70/T70_FF.csv
  spice/simulations/T70/T70_FS.csv
  spice/simulations/T70/T70_SF.csv
  spice/simulations/T70/T70_SS.csv
  spice/simulations/T70/T70_TT.csv
  spice/simulations/d-flip-flop.csv
  spice/simulations/one-bit-register-FF.csv
  spice/simulations/one-bit-register-SS.csv
  spice/simulations/one-bit-register-TT.csv
  spice/src/circuits/mux.cir
  spice/src/main.cir
Labels: enhancement

#27 feat: static power consumption
  .gitignore
  spice/plots/Current_T27_FF.png
  spice/plots/Current_T27_TT.png
  spice/plots/T0/T0_FF.png
  spice/plots/T0/T0_FS.png
  spice/plots/T0/T0_SF.png
  spice/plots/T0/T0_SS.png
  spice/plots/T0/T0_TT.png
  spice/plots/T27/T27_FF.png
  spice/plots/T27/T27_FS.png
  spice/plots/T27/T27_SF.png
  spice/plots/T27/T27_SS.png
  spice/plots/T27/T27_TT.png
  spice/plots/T70/T70_FF.png
  spice/plots/T70/T70_FS.png
  spice/plots/T70/T70_SF.png
  spice/plots/T70/T70_SS.png
  spice/plots/T70/T70_TT.png
  spice/plots/main.py
  spice/plots/power.py
  spice/simulations/T0/T0_FF.csv
  spice/simulations/T0/T0_FS.csv
  spice/simulations/T0/T0_SF.csv
  spice/simulations/T0/T0_SS.csv
  spice/simulations/T0/T0_TT.csv
  spice/simulations/T27/T27_FF.csv
  spice/simulations/T27/T27_FS.csv
  spice/simulations/T27/T27_SF.csv
  spice/simulations/T27/T27_SS.csv
  spice/simulations/T27/T27_TT.csv
  spice/simulations/T70/T70_FF.csv
  spice/simulations/T70/T70_FS.csv
  spice/simulations/T70/T70_SF.csv
  spice/simulations/T70/T70_SS.csv
  spice/simulations/T70/T70_TT.csv
  spice/src/circuits/gates.cir
  spice/src/main.cir
Labels: enhancement, Spice

#29 Verilog Implementation of MAC Unit
  verilog/src/adder/8_bit_adder.v
  verilog/src/complete_circuits/mac_unit.v
  verilog/testbench/adder_tb/8_bit_adder_tb.v
  verilog/testbench/complete_circuits/mac_unit_tb.v
Labels: enhancement, Verilog
